### ISSUE TITLE
ClosedXML.Parser 1.2.0 not compatible with '.NETFramework,Version=v4.8'

### ISSUE THREAD

**Issue by alborl84** [ClosedXML/ClosedXML.Parser#21]
when I install ClosedXML.Parser 1.2.0 with
NuGet\Install-Package ClosedXML.Parser
I get the following error:
You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework.

Since ClosedXML.Parser is referenced by the latest version of ClosedXML that still compatible with framework 4.8 I think you should solve the compatibility issue, else new versions of ClosedXML cannot be installed into any project that targer framework 4.8

**Comment by jahav** [comment]
Package does contain a version support netstandard2.0 (see https://nuget.info/packages/ClosedXML.Parser/1.2.0). Net462+ support netstandard2.0. I have also verified that it does work, both using SDK and old style projects.

Unreproducible. Closing.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="ClosedXML.Parser" Version="1.3.0" />
    <PackageReference Include="System.IO.Packaging" Version="8.0.1" />
  </ItemGroup>

</Project>
```

```csharp
using System;
using ClosedXML.Excel;

namespace ConsoleApp8
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("Original");
                ws.Cell("A1").Value = "hello";
                wb.SaveAs(@"C:\Temp\test.xlsx");
                Console.ReadKey();
            }
        }
    }
}
```
